server:
  port: 3344

spring:
  application:
    name: cloud-config-center

  cloud:
    config:
      server:
        git:
          uri: https://github.com.cnpmjs.org/qq1477959747/com.lrc.springcloud.git
          search-paths:
            - cloud-config-center3344/MyConfig
          default-label:  master
          username: 1477959747@qq.com
          password: qq19990601
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
