server:
  port: 80

spring:
  application:
    name: cloud-order-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001:7001/eureka/,http://eureka7002:7002/eureka/,http://eureka7003:7003/eureka/
  instance:
    instance-id: hystrixorder80
    prefer-ip-address: true

#ribbon:
#  ConnectTimeout: 5000
#  ReadTimeout: 5000
feign:
  client:
    config:
      default:
        ConnectTimeout: 5000
        ReadTimeout: 5000
  circuitbreaker:
    enabled: true

logging:
  level:
    com.lrc.hystrix.springcloud.service.PaymentHystrixService: debug
