server:
  port: 9527
spring:
  application:
    name: cloud-gatewy
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名创建路由
      routes:
        - id: payment_routh
          uri: lb://cloud-payment-hystrix-service
          predicates:
            - Path=/payment/get/**
        - id: payment_routh2
          uri: lb://cloud-payment-hystrix-service
          predicates:
            - Path=/payment/hystrix/**
        - id: payment_routh2
          uri: lb://cloud-payment-hystrix-service
          predicates:
            - Path=/payment/lb/**
            - After=2021-08-10T23:17:58.279+08:00[Asia/Shanghai]
            - Cookie=username,lrc

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      defaultZone: http://eureka7001:7001/eureka/
    register-with-eureka: true
    fetch-registry: true
